### ISSUE TITLE
About hard_index

### ISSUE THREAD

**Issue by jiujiangluck** [MichiganCOG/A2CL-PT#2]
I am sorry to intertrupt you. I have a question about hard index.
In your paper, the hard index follows:
![Screenshot from 2020-08-29 16-06-38](https://user-images.githubusercontent.com/16516223/91632170-ab72ea00-ea11-11ea-8326-552d9e9aaf41.png)
But it uses `max function` in backward in your code. Why?

`forward`
https://github.com/MichiganCOG/A2CL-PT/blob/493fb6e23b60f5a4ba52c596f9c95be86dc33b1a/losses.py#L45-L47

`backward`
https://github.com/MichiganCOG/A2CL-PT/blob/493fb6e23b60f5a4ba52c596f9c95be86dc33b1a/losses.py#L66-L68

**Comment by kylemin** [comment]
Hi,
Thank you for your interest!
That is because distmat's are defined differently in the forward and the backward functions.
Please refer to lines 39 and 60 (torch.acos and torch.mm are used, respectively).
Thank you.
Kyle
